apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yantra4d

resources:
- namespace.yaml
- yantra4d-backend-deployment.yaml
- yantra4d-backend-service.yaml
- yantra4d-studio-deployment.yaml
- yantra4d-studio-service.yaml
- yantra4d-landing-deployment.yaml
- yantra4d-landing-service.yaml
- yantra4d-admin-deployment.yaml
- yantra4d-admin-service.yaml
- yantra4d-analytics-pvc.yaml
- yantra4d-redis-pvc.yaml
- yantra4d-redis-deployment.yaml
- yantra4d-redis-service.yaml

images:
- digest: sha256:d8b84f3c5bc2c79aac1246c71b377dc55b351b5c37f550d82dd4f7994eb20b98
  name: ghcr.io/madfam-org/yantra4d/admin
  newName: ghcr.io/madfam-org/yantra4d/admin
- digest: sha256:de77e23591766747257ea80d65eec202fa50f54ba96793b12d3fde8ccf2bbde9
  name: ghcr.io/madfam-org/yantra4d/backend
  newName: ghcr.io/madfam-org/yantra4d/backend
- digest: sha256:bbe71f2baf8202fd60b1398a0e670ea74abda2c0411965dc0f6f9aded8da6aa3
  name: ghcr.io/madfam-org/yantra4d/landing
  newName: ghcr.io/madfam-org/yantra4d/landing
- digest: sha256:1374023e3d86a552427b7683eff90b9749195259f662cf5a19e8f84e6c3a8a82
  name: ghcr.io/madfam-org/yantra4d/studio
  newName: ghcr.io/madfam-org/yantra4d/studio
