apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yantra4d

resources:
- namespace.yaml
- yantra4d-backend-deployment.yaml
- yantra4d-backend-service.yaml
- yantra4d-studio-deployment.yaml
- yantra4d-studio-service.yaml
- yantra4d-landing-deployment.yaml
- yantra4d-landing-service.yaml
- yantra4d-admin-deployment.yaml
- yantra4d-admin-service.yaml
- yantra4d-analytics-pvc.yaml
- yantra4d-redis-pvc.yaml
- yantra4d-redis-deployment.yaml
- yantra4d-redis-service.yaml

images:
- digest: sha256:d8b84f3c5bc2c79aac1246c71b377dc55b351b5c37f550d82dd4f7994eb20b98
  name: ghcr.io/madfam-org/yantra4d/admin
  newName: ghcr.io/madfam-org/yantra4d/admin
- digest: sha256:539c4690fe048d015eaa38a70fb5f0b3031c018fc8681ff617ddcd7e7dbab884
  name: ghcr.io/madfam-org/yantra4d/backend
  newName: ghcr.io/madfam-org/yantra4d/backend
- digest: sha256:d6f6fd15007c28878db9c9b2c6fb18b7ad706fc39681d0c8dbb048e4ce9bde7b
  name: ghcr.io/madfam-org/yantra4d/landing
  newName: ghcr.io/madfam-org/yantra4d/landing
- digest: sha256:cea595e74046bb46739af4bf70c4633175f5e34e0bb2c4cf957e8b84ae231968
  name: ghcr.io/madfam-org/yantra4d/studio
  newName: ghcr.io/madfam-org/yantra4d/studio
